import './spinner';
import './films';
import './apiFilms/apiSearch';
import './modal';
// import './pagination';
import './modal-team';
import './login';
import './theme';
import './fetchTrailer';
import './onScrollButtonClick';
